const ICONS={grid:'<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></svg>',clock:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>',receipt:'<svg viewBox="0 0 24 24"><path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Z"/><path d="M9 8h6M9 12h6"/></svg>',chart:'<svg viewBox="0 0 24 24"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>',settings:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19 13.5v-3l-2-.7-.7-1.7.9-2-2.1-2.1-2 .9-1.7-.7-.7-2h-3l-.7 2-1.7.7-2-.9-2.1 2.1.9 2-.7 1.7-2 .7v3l2 .7.7 1.7-.9 2 2.1 2.1 2-.9 1.7.7.7 2h3l.7-2 1.7-.7 2 .9 2.1-2.1-.9-2 .7-1.7 2-.7Z"/></svg>',calendar:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4M16 3v4M3 10h18"/></svg>',chevron:'<svg viewBox="0 0 24 24"><path d="m8 10 4 4 4-4"/></svg>',moon:'<svg viewBox="0 0 24 24"><path d="M20 15.5A8.5 8.5 0 0 1 8.5 4 8.5 8.5 0 1 0 20 15.5Z"/></svg>',plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',briefcase:'<svg viewBox="0 0 24 24"><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M9 7V4h6v3M3 12h18"/></svg>',edit:'<svg viewBox="0 0 24 24"><path d="m4 20 4.5-1 10-10a2.1 2.1 0 0 0-3-3l-10 10L4 20Z"/></svg>',play:'<svg viewBox="0 0 24 24"><path d="m8 5 11 7-11 7V5Z"/></svg>',stop:'<svg viewBox="0 0 24 24"><rect x="6" y="6" width="12" height="12" rx="2"/></svg>',wallet:'<svg viewBox="0 0 24 24"><path d="M4 6h14a2 2 0 0 1 2 2v11H4a2 2 0 0 1-2-2V6a3 3 0 0 1 3-3h12"/><path d="M15 11h5v4h-5a2 2 0 0 1 0-4Z"/></svg>',arrow:'<svg viewBox="0 0 24 24"><path d="M5 12h14M14 7l5 5-5 5"/></svg>',search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',filter:'<svg viewBox="0 0 24 24"><path d="M4 6h16M7 12h10M10 18h4"/></svg>',download:'<svg viewBox="0 0 24 24"><path d="M12 3v12M7 10l5 5 5-5M4 20h16"/></svg>',upload:'<svg viewBox="0 0 24 24"><path d="M12 16V4M7 9l5-5 5 5M4 20h16"/></svg>',menu:'<svg viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></svg>',check:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="m8 12 2.5 2.5L16 9"/></svg>',trash:'<svg viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14M10 11v6M14 11v6"/></svg>'};
const CURRENCIES={USD:'USD — US Dollar',ILS:'ILS — Israeli Shekel',INR:'INR — Indian Rupee',EUR:'EUR — Euro',GBP:'GBP — British Pound',CHF:'CHF — Swiss Franc',SEK:'SEK — Swedish Krona',NOK:'NOK — Norwegian Krone',DKK:'DKK — Danish Krone',PLN:'PLN — Polish Zloty',CZK:'CZK — Czech Koruna',HUF:'HUF — Hungarian Forint',RON:'RON — Romanian Leu',TRY:'TRY — Turkish Lira',JPY:'JPY — Japanese Yen',CNY:'CNY — Chinese Yuan',HKD:'HKD — Hong Kong Dollar',SGD:'SGD — Singapore Dollar',KRW:'KRW — South Korean Won',THB:'THB — Thai Baht',MYR:'MYR — Malaysian Ringgit',IDR:'IDR — Indonesian Rupiah',PHP:'PHP — Philippine Peso',AED:'AED — UAE Dirham'};
const DEFAULT_SETTINGS={name:'Alex Verne',workspace:'Freelance workspace',goal:40,currency:'USD',rates:{USD:1,ILS:.27,INR:.012,EUR:1.08,GBP:1.37,CHF:1.25,SEK:.106,NOK:.098,DKK:.157,PLN:.276,CZK:.048,HUF:.003,RON:.232,TRY:.025,JPY:.0067,CNY:.139,HKD:.128,SGD:.78,KRW:.00073,THB:.03,MYR:.235,IDR:.000061,PHP:.0175,AED:.2723}};
const DEFAULT_JOBS=[{id:1,name:'Arc Studio',color:'#ef7c57',rate:85,currency:'USD'},{id:2,name:'Northstar',color:'#25a988',rate:110,currency:'USD'},{id:3,name:'Personal',color:'#efa940',rate:0,currency:'USD'}];
const DEFAULT_CATEGORIES=['Software','Travel','Meals','Equipment','Other'];
const today=new Date(),isoToday=toISO(today);
function toISO(date){const d=new Date(date);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function dayOffset(n){const d=new Date(today);d.setDate(d.getDate()+n);return toISO(d)}
const DEFAULT_TIME=[
  {id:1,description:'Product dashboard polish',job:'Arc Studio',date:isoToday,start:'09:15',end:'11:45',hours:2.5,rate:85,currency:'USD',billable:true},
  {id:2,description:'Client discovery call',job:'Northstar',date:isoToday,start:'12:30',end:'13:15',hours:.75,rate:110,currency:'USD',billable:true},
  {id:3,description:'Research & moodboard',job:'Arc Studio',date:dayOffset(-1),start:'10:00',end:'13:20',hours:3.33,rate:85,currency:'USD',billable:true},
  {id:4,description:'Portfolio administration',job:'Personal',date:dayOffset(-2),start:'15:00',end:'16:10',hours:1.17,rate:0,currency:'USD',billable:false},
  {id:5,description:'Design system handoff',job:'Northstar',date:dayOffset(-3),start:'09:00',end:'12:45',hours:3.75,rate:110,currency:'USD',billable:true},
  {id:6,description:'Mobile wireframes',job:'Arc Studio',date:dayOffset(-8),start:'10:00',end:'15:30',hours:5.5,rate:85,currency:'USD',billable:true},
  {id:7,description:'Workshop preparation',job:'Northstar',date:dayOffset(-15),start:'09:30',end:'14:00',hours:4.5,rate:110,currency:'USD',billable:true}
];
const DEFAULT_EXPENSES=[
  {id:11,name:'Figma Professional',amount:15,category:'Software',job:'Arc Studio',date:isoToday,currency:'USD',notes:''},
  {id:12,name:'Train to client workshop',amount:178,category:'Travel',job:'Northstar',date:dayOffset(-1),currency:'ILS',notes:''},
  {id:13,name:'Team lunch',amount:86,category:'Meals',job:'Northstar',date:dayOffset(-2),currency:'USD',notes:''},
  {id:14,name:'Studio monitor',amount:495,category:'Equipment',job:'Personal',date:dayOffset(-10),currency:'EUR',notes:''},
  {id:15,name:'Prototype assets',amount:2400,category:'Software',job:'Arc Studio',date:dayOffset(-18),currency:'INR',notes:''}
];

let settings={...DEFAULT_SETTINGS,...readJSON('tw-settings',{}),rates:{...DEFAULT_SETTINGS.rates,...readJSON('tw-settings',{}).rates}};
let jobs=readJSON('tw-jobs',DEFAULT_JOBS);let categories=readJSON('tw-categories',DEFAULT_CATEGORIES);
let timeEntries=readJSON('tw-time',DEFAULT_TIME).map(x=>({...x,job:x.job||x.project||jobs[0].name,currency:x.currency||'USD'}));
let expenses=readJSON('tw-expenses',DEFAULT_EXPENSES).map(x=>({...x,job:x.job||x.project||jobs[0].name,currency:x.currency||'USD'}));
let currentFeed='all',modalType='time',editingId=null,pendingReceipt='',timerStart=null,timerTick=null,overviewPeriod='week',selectedJob='all',rateStatus='Updating live rates…',rateUpdatedAt=localStorage.getItem('tw-rate-updated')||'';

function readJSON(key,fallback){try{const value=localStorage.getItem(key);return value?JSON.parse(value):structuredClone(fallback)}catch{return structuredClone(fallback)}}
function persist(){localStorage.setItem('tw-settings',JSON.stringify(settings));localStorage.setItem('tw-jobs',JSON.stringify(jobs));localStorage.setItem('tw-categories',JSON.stringify(categories));localStorage.setItem('tw-time',JSON.stringify(timeEntries));localStorage.setItem('tw-expenses',JSON.stringify(expenses))}
function decorateIcons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=ICONS[el.dataset.icon]||''});root.querySelectorAll('svg').forEach(svg=>{if(!svg.closest('.brand-mark')){svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.8');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round')}})}
function convert(amount,from=settings.currency,to=settings.currency){const usd=Number(amount||0)*(settings.rates[from]||1);return usd/(settings.rates[to]||1)}
function money(amount,currency=settings.currency){try{return new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:2}).format(amount)}catch{return `${currency} ${Number(amount).toFixed(2)}`}}
function shortDate(s){const d=new Date(`${s}T12:00:00`);return `${String(d.getDate()).padStart(2,'0')}-${d.toLocaleDateString('en-US',{month:'short'}).toUpperCase()}-${d.getFullYear()}`}
function duration(h){const hrs=Math.floor(h),mins=Math.round((h-hrs)*60);return hrs?`${hrs}h ${mins?mins+'m':''}`:`${mins}m`}
function startOfWeek(date=today){const d=new Date(date);const day=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day);return d}
function inPeriod(date,period){if(period==='all')return true;const d=new Date(`${date}T12:00:00`),now=new Date(today);if(period==='week'){const start=startOfWeek(now),end=new Date(start);end.setDate(end.getDate()+7);return d>=start&&d<end}return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}
function getJob(name){return jobs.find(j=>j.name===name)||jobs[0]||{name:'General',color:'#6157df',rate:0,currency:settings.currency}}
function projectDot(name){return `<i class="project-dot" style="--dot:${getJob(name).color}"></i>`}
function filterBySelectedJob(list){return selectedJob==='all'?list:list.filter(x=>x.job===selectedJob)}
function safeText(value=''){return String(value).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}

function setSelectOptions(select,items,allLabel,current){if(!select)return;const old=current??select.value;select.innerHTML=(allLabel?`<option value="all">${allLabel}</option>`:'')+items.map(x=>`<option value="${safeText(x)}">${safeText(x)}</option>`).join('');if([...select.options].some(o=>o.value===old))select.value=old}
function renderDynamicControls(){
  const jobNames=jobs.map(j=>j.name);setSelectOptions(document.getElementById('timeJobFilter'),jobNames,'All jobs');setSelectOptions(document.getElementById('expenseJobFilter'),jobNames,'All jobs');setSelectOptions(document.getElementById('categoryFilter'),categories,'All categories');
  document.querySelectorAll('select[name="project"],select[name="expenseProject"],#timerProject').forEach(s=>setSelectOptions(s,jobNames,null,s.value||jobs[0]?.name));
  document.querySelectorAll('select[name="category"]').forEach(s=>setSelectOptions(s,categories,null,s.value||categories[0]));
  document.querySelectorAll('.currency-select').forEach(s=>{const old=s.value||settings.currency;s.innerHTML=Object.entries(CURRENCIES).map(([v,l])=>`<option value="${v}">${l}</option>`).join('');s.value=old});
  [document.getElementById('quickCurrency'),document.getElementById('settingCurrency')].forEach(s=>{if(!s)return;s.innerHTML=Object.entries(CURRENCIES).map(([v,l])=>`<option value="${v}">${l}</option>`).join('');s.value=settings.currency});
  document.getElementById('jobNav').innerHTML=`<button class="${selectedJob==='all'?'active':''}" data-job-nav="all"><span class="project-dot" style="--dot:#6157df"></span>All jobs</button>`+jobs.map(j=>`<button class="${selectedJob===j.name?'active':''}" data-job-nav="${safeText(j.name)}">${projectDot(j.name)}${safeText(j.name)}</button>`).join('');
}
function periodData(){return{times:filterBySelectedJob(timeEntries).filter(x=>inPeriod(x.date,overviewPeriod)),costs:filterBySelectedJob(expenses).filter(x=>inPeriod(x.date,overviewPeriod))}}
function renderOverview(){
  const {times,costs}=periodData(),hrs=times.reduce((s,x)=>s+x.hours,0),earned=times.reduce((s,x)=>s+convert(x.hours*x.rate,x.currency),0),spent=costs.reduce((s,x)=>s+convert(x.amount,x.currency),0),net=earned-spent;
  document.getElementById('hoursMetric').textContent=duration(hrs);document.getElementById('earningsMetric').textContent=money(earned);document.getElementById('expensesMetric').textContent=money(spent);document.getElementById('incomeSummary').textContent=money(earned);document.getElementById('expenseSummary').textContent=money(spent);document.getElementById('netMetric').textContent=money(net).replace(/\.00$/,'');
  document.getElementById('hoursPeriodLabel').textContent=`Hours this ${overviewPeriod}`;document.querySelector('.metric-card.purple p').textContent='Actual tracked time';document.querySelector('.metric-card.mint p').textContent=`converted to ${settings.currency} across ${new Set(times.map(x=>x.job)).size} jobs`;document.querySelector('.metric-card.peach p').textContent=`${costs.length} recorded this ${overviewPeriod}`;
  const total=Math.max(earned+spent,1),incomePct=Math.max(0,Math.min(100,earned/total*100));document.getElementById('donut').style.background=`conic-gradient(var(--purple) 0 ${incomePct}%,#f0b39d ${incomePct}% 100%)`;
  document.getElementById('walletPeriodLabel').textContent=overviewPeriod==='week'?'Current week':'Current month';updateTodayTotal();
  renderChart(times);renderActivity();
}
function renderChart(times){
  let groups=[];
  if(overviewPeriod==='week'){const start=startOfWeek();groups=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return{label:d.toLocaleDateString('en-US',{weekday:'short'}),date:toISO(d)}}).map(g=>{const rows=times.filter(x=>x.date===g.date);return{d:g.label,b:rows.filter(x=>x.billable).reduce((s,x)=>s+x.hours,0),n:rows.filter(x=>!x.billable).reduce((s,x)=>s+x.hours,0)}});document.getElementById('activityChartTitle').textContent='Weekly activity';document.getElementById('activityChartSubtitle').textContent='Time tracked by day'}else{const visibleJobs=selectedJob==='all'?jobs:jobs.filter(j=>j.name===selectedJob);groups=visibleJobs.map(j=>{const rows=times.filter(x=>x.job===j.name);return{d:j.name,b:rows.filter(x=>x.billable).reduce((s,x)=>s+x.hours,0),n:rows.filter(x=>!x.billable).reduce((s,x)=>s+x.hours,0)}});document.getElementById('activityChartTitle').textContent='Monthly activity by job';document.getElementById('activityChartSubtitle').textContent='Billable and non-billable hours for each job'}
  const max=Math.max(8,...groups.map(x=>x.b+x.n));document.getElementById('barChart').innerHTML=groups.map(x=>`<div class="bar-day"><span class="billable" title="${duration(x.b)} billable" style="height:${x.b/max*100}%"></span><span class="nonbillable" title="${duration(x.n)} non-billable" style="height:${x.n/max*100}%"></span><label>${x.d}</label></div>`).join('');
}
function renderActivity(){const {times,costs}=periodData();const combined=[...times.map(x=>({...x,type:'time',sort:x.date,description:x.description||'—',earning:x.rate?money(x.hours*x.rate,x.currency):'—'})),...costs.map(x=>({...x,type:'expense',sort:x.date,start:'—',end:'—',description:`${x.name}${x.category?` · ${x.category}`:''}`,earning:`-${money(x.amount,x.currency)}`}))].filter(x=>currentFeed==='all'||x.type===currentFeed).sort((a,b)=>b.sort.localeCompare(a.sort)).slice(0,5);document.getElementById('activityList').innerHTML=`<div class="activity-grid activity-header"><span>Job</span><span>Date</span><span>Starting</span><span>Closing</span><span>Earning</span><span>Description</span></div>`+(combined.map(x=>`<div class="activity-grid"><span class="activity-job">${projectDot(x.job)}${safeText(x.job)}</span><span>${shortDate(x.date)}</span><span>${safeText(x.start)}</span><span>${safeText(x.end)}</span><strong class="${x.type==='expense'?'negative':''}">${x.earning}</strong><span class="activity-description">${safeText(x.description)}</span></div>`).join('')||'<div class="empty-state">No entries match this period.</div>')}
function filteredTimes(){const q=document.getElementById('timeSearch').value.toLowerCase(),period=document.getElementById('timePeriodFilter').value,job=document.getElementById('timeJobFilter').value,type=document.getElementById('billableFilter').value;return timeEntries.filter(x=>(x.description+x.job).toLowerCase().includes(q)&&inPeriod(x.date,period)&&(job==='all'||x.job===job)&&(type==='all'||(type==='billable')===!!x.billable))}
function filteredExpenses(){const q=document.getElementById('expenseSearch').value.toLowerCase(),period=document.getElementById('expensePeriodFilter').value,job=document.getElementById('expenseJobFilter').value,cat=document.getElementById('categoryFilter').value;return expenses.filter(x=>(x.name+x.job+x.category).toLowerCase().includes(q)&&inPeriod(x.date,period)&&(job==='all'||x.job===job)&&(cat==='all'||x.category===cat))}
function renderTables(){
  const ts=filteredTimes();document.getElementById('timeTable').innerHTML=`<div class="table-row time-row header"><span>Job</span><span>Date</span><span>Starting time</span><span>Closing time</span><span>Earning</span><span>Description</span><span></span></div>`+ts.map(x=>`<div class="table-row time-row"><span class="pill purple">${projectDot(x.job)} ${safeText(x.job)}</span><span>${shortDate(x.date)}</span><span>${x.start}</span><span>${x.end}</span><strong>${x.rate?money(x.hours*x.rate,x.currency):'—'}</strong><span class="table-title">${safeText(x.description||'—')}</span><span class="row-actions"><button class="row-action" data-edit-time="${x.id}" aria-label="Edit time entry">${ICONS.edit}</button><button class="row-action danger" data-delete-time="${x.id}" aria-label="Delete time entry">${ICONS.trash}</button></span></div>`).join('')||'<div class="empty-state">No time entries match these filters.</div>';
  const es=filteredExpenses();document.getElementById('expenseTable').innerHTML=`<div class="table-row expense-row header"><span>Expense</span><span>Category</span><span>Job</span><span>Date</span><span>Amount</span><span>Receipt</span><span></span></div>`+es.map(x=>`<div class="table-row expense-row"><div><span class="table-title">${safeText(x.name)}</span><span class="table-sub">${safeText(x.notes||'Recorded expense')}</span></div><span class="pill">${safeText(x.category)}</span><span>${projectDot(x.job)} ${safeText(x.job)}</span><span>${shortDate(x.date)}</span><strong>${money(x.amount,x.currency)}</strong><span>${x.receipt?`<img class="receipt-thumb" src="${x.receipt}" alt="Receipt for ${safeText(x.name)}">`:'—'}</span><span class="row-actions"><button class="row-action" data-edit-expense="${x.id}" aria-label="Edit ${safeText(x.name)}">${ICONS.edit}</button><button class="row-action danger" data-delete-expense="${x.id}" aria-label="Delete ${safeText(x.name)}">${ICONS.trash}</button></span></div>`).join('')||'<div class="empty-state">No expenses match these filters.</div>';decorateIcons(document.getElementById('timeTable'));decorateIcons(document.getElementById('expenseTable'))
}
function renderStats(){const ts=filteredTimes(),es=filteredExpenses(),hrs=ts.reduce((s,x)=>s+x.hours,0),earned=ts.reduce((s,x)=>s+convert(x.hours*x.rate,x.currency),0),billable=ts.filter(x=>x.billable).reduce((s,x)=>s+x.hours,0),spent=es.reduce((s,x)=>s+convert(x.amount,x.currency),0);document.getElementById('timeStats').innerHTML=`<div class="mini-stat"><span>Filtered time</span><strong>${duration(hrs)}</strong></div><div class="mini-stat"><span>Billable hours</span><strong>${duration(billable)}</strong></div><div class="mini-stat"><span>Earnings in ${settings.currency}</span><strong>${money(earned)}</strong></div>`;const topCat=Object.entries(es.reduce((a,x)=>(a[x.category]=(a[x.category]||0)+convert(x.amount,x.currency),a),{})).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';document.getElementById('expenseStats').innerHTML=`<div class="mini-stat"><span>Filtered expenses</span><strong>${money(spent)}</strong></div><div class="mini-stat"><span>Entries</span><strong>${es.length}</strong></div><div class="mini-stat"><span>Top category</span><strong>${topCat}</strong></div>`;document.getElementById('expenseBadge').textContent=expenses.length}
function renderReports(){const projects=jobs.map(j=>{const ptime=timeEntries.filter(x=>x.job===j.name),income=ptime.reduce((s,x)=>s+convert(x.hours*x.rate,x.currency),0),cost=expenses.filter(x=>x.job===j.name).reduce((s,x)=>s+convert(x.amount,x.currency),0),hours=ptime.reduce((s,x)=>s+x.hours,0);return{name:j.name,color:j.color,income,cost,hours,profit:income-cost}}),max=Math.max(...projects.map(x=>x.profit),1),totalHours=projects.reduce((s,x)=>s+x.hours,0);document.getElementById('profitabilityChart').innerHTML=projects.map(x=>`<div class="profit-row"><span>${projectDot(x.name)} ${safeText(x.name)}</span><div class="profit-bar"><i style="width:${Math.max(4,x.profit/max*100)}%;background:${x.color}"></i></div><strong>${money(x.profit)}</strong></div>`).join('');document.getElementById('projectLegend').innerHTML=projects.map(x=>`<div class="project-legend-row"><span>${projectDot(x.name)}${safeText(x.name)}</span><strong>${duration(x.hours)}</strong></div>`).join('');document.querySelector('.report-donut strong').textContent=duration(totalHours)}
function renderSettings(){document.getElementById('settingName').value=settings.name;document.getElementById('settingWorkspace').value=settings.workspace;document.getElementById('settingCurrency').value=settings.currency;const usdInr=1/(settings.rates.INR||DEFAULT_SETTINGS.rates.INR),ilsInr=(settings.rates.ILS||DEFAULT_SETTINGS.rates.ILS)/(settings.rates.INR||DEFAULT_SETTINGS.rates.INR);document.getElementById('rateGrid').innerHTML=`<div class="live-rate-card"><span>USD → INR</span><strong>1 USD = ${usdInr.toFixed(2)} INR</strong></div><div class="live-rate-card"><span>ILS → INR</span><strong>1 ILS = ${ilsInr.toFixed(2)} INR</strong></div>`;document.getElementById('usdInrRate').textContent=usdInr.toFixed(2);document.getElementById('ilsInrRate').textContent=ilsInr.toFixed(2);document.getElementById('liveRateStatus').textContent=rateStatus;document.getElementById('settingsRateStatus').textContent=rateStatus;document.getElementById('jobList').innerHTML=jobs.map(j=>`<div class="manage-row" data-job-row="${j.id}"><input class="mini-color" type="color" value="${j.color}" aria-label="${safeText(j.name)} color"><input class="manage-name" value="${safeText(j.name)}" aria-label="Job name"><input class="manage-rate" type="number" min="0" step="1" value="${j.rate}" aria-label="Default hourly rate"><select class="manage-currency">${Object.keys(CURRENCIES).map(c=>`<option ${c===j.currency?'selected':''}>${c}</option>`).join('')}</select><button class="row-action save-manage" data-save-job="${j.id}" aria-label="Save job">${ICONS.check}</button><button class="row-action danger" data-delete-job="${j.id}" aria-label="Delete job">${ICONS.trash}</button></div>`).join('');document.getElementById('categoryList').innerHTML=categories.map((c,i)=>`<div class="manage-row category-manage"><input class="manage-name" value="${safeText(c)}" aria-label="Category name"><button class="row-action save-manage" data-save-category="${i}" aria-label="Save category">${ICONS.check}</button><button class="row-action danger" data-delete-category="${i}" aria-label="Delete category">${ICONS.trash}</button></div>`).join('');decorateIcons(document.getElementById('settingsView'))}
function updateIdentity(){document.getElementById('sidebarUser').textContent=settings.name;document.getElementById('sidebarWorkspace').textContent=settings.workspace;document.querySelector('.avatar').textContent=settings.name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();document.getElementById('todayLabel').textContent=`${today.toLocaleDateString('en-US',{weekday:'long'}).toUpperCase()} · ${shortDate(isoToday)}`}
function renderAll(){renderDynamicControls();renderOverview();renderTables();renderStats();renderReports();renderSettings();updateIdentity();persist()}

function setView(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(`${view}View`).classList.add('active');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const greeting=`Good ${today.getHours()<12?'morning':today.getHours()<18?'afternoon':'evening'}, ${settings.name.split(' ')[0]}`;const titles={dashboard:greeting,time:'Track your time',expenses:'Manage expenses',reports:'Insights & reports',settings:'Your settings'};document.getElementById('pageTitle').textContent=titles[view];document.querySelector('.sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)setView(nav.dataset.view);const jobNav=e.target.closest('[data-job-nav]');if(jobNav){selectedJob=jobNav.dataset.jobNav;renderAll()}const editExpense=e.target.closest('[data-edit-expense]');if(editExpense)openModal('expense',Number(editExpense.dataset.editExpense));const editTime=e.target.closest('[data-edit-time]');if(editTime)openModal('time',Number(editTime.dataset.editTime));const deleteExpense=e.target.closest('[data-delete-expense]');if(deleteExpense&&confirm('Delete this expense entry?')){expenses=expenses.filter(x=>x.id!==Number(deleteExpense.dataset.deleteExpense));renderAll();showToast('Expense deleted')}const deleteTime=e.target.closest('[data-delete-time]');if(deleteTime&&confirm('Delete this time entry?')){timeEntries=timeEntries.filter(x=>x.id!==Number(deleteTime.dataset.deleteTime));renderAll();showToast('Time entry deleted')}});
document.querySelector('.view-all').addEventListener('click',()=>setView('time'));document.getElementById('mobileMenu').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));document.getElementById('profileSettings').addEventListener('click',()=>setView('settings'));document.getElementById('quickJob').addEventListener('click',()=>{setView('settings');setTimeout(()=>document.getElementById('newJobName').focus(),100)});
document.querySelectorAll('[data-period]').forEach(b=>b.addEventListener('click',()=>{overviewPeriod=b.dataset.period;document.querySelectorAll('[data-period]').forEach(x=>x.classList.toggle('active',x===b));renderOverview()}));

const backdrop=document.getElementById('modalBackdrop');
function applyJobDefaults(jobName){const job=getJob(jobName),form=document.getElementById('entryForm');form.elements.rate.value=job.rate;form.elements.timeCurrency.value=job.currency;form.elements.billable.checked=job.rate>0}
function renderReceiptPreview(){const box=document.getElementById('receiptPreview');box.innerHTML=pendingReceipt?`<img src="${pendingReceipt}" alt="Expense receipt preview"><button type="button" class="secondary-btn" id="removeReceipt">Remove image</button>`:'<span>No receipt image selected</span>';document.getElementById('removeReceipt')?.addEventListener('click',()=>{pendingReceipt='';document.querySelector('[name="receiptImage"]').value='';renderReceiptPreview()})}
function openModal(type='time',id=null){modalType=type;editingId=id;pendingReceipt='';backdrop.classList.add('open');backdrop.setAttribute('aria-hidden','false');switchEntry(type);const form=document.getElementById('entryForm');form.reset();renderDynamicControls();form.elements.date.value=isoToday;form.elements.expenseDate.value=isoToday;if(type==='time'&&id){const x=timeEntries.find(x=>x.id===id);form.elements.description.value=x.description||'';form.elements.project.value=x.job;form.elements.date.value=x.date;form.elements.start.value=x.start;form.elements.end.value=x.end;form.elements.rate.value=x.rate;form.elements.timeCurrency.value=x.currency;form.elements.billable.checked=x.billable}else if(type==='expense'&&id){const x=expenses.find(x=>x.id===id);form.elements.expenseName.value=x.name;form.elements.amount.value=x.amount;form.elements.expenseDate.value=x.date;form.elements.category.value=x.category;form.elements.expenseProject.value=x.job;form.elements.expenseCurrency.value=x.currency;form.elements.notes.value=x.notes||'';pendingReceipt=x.receipt||''}else if(type==='time'){applyJobDefaults(form.elements.project.value)}renderReceiptPreview();document.getElementById('modalTitle').textContent=`${id?'Edit':'Add'} ${type==='time'?'time entry':'an expense'}`;setTimeout(()=>form.elements[type==='time'?'description':'expenseName'].focus(),100)}
function closeModal(){backdrop.classList.remove('open');backdrop.setAttribute('aria-hidden','true');editingId=null;pendingReceipt='';document.getElementById('entryForm').reset()}
function switchEntry(type){modalType=type;document.querySelectorAll('.entry-switch button').forEach(b=>b.classList.toggle('active',b.dataset.type===type));const time=document.getElementById('timeFields'),expense=document.getElementById('expenseFields');time.classList.toggle('hidden',type!=='time');expense.classList.toggle('hidden',type!=='expense');time.querySelectorAll('input,select,textarea').forEach(x=>x.disabled=type!=='time');expense.querySelectorAll('input,select,textarea').forEach(x=>x.disabled=type!=='expense');document.getElementById('modalTitle').textContent=type==='time'?'Add time entry':'Add an expense'}
document.getElementById('quickAdd').addEventListener('click',()=>openModal('time'));document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.open)));document.getElementById('closeModal').addEventListener('click',closeModal);document.getElementById('cancelModal').addEventListener('click',closeModal);backdrop.addEventListener('click',e=>{if(e.target===backdrop)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});document.querySelectorAll('.entry-switch button').forEach(b=>b.addEventListener('click',()=>switchEntry(b.dataset.type)));
document.getElementById('entryForm').elements.project.addEventListener('change',e=>applyJobDefaults(e.target.value));
document.querySelector('[name="receiptImage"]').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;if(file.size>1.5*1024*1024){e.target.value='';showToast('Receipt image must be under 1.5 MB');return}const reader=new FileReader();reader.onload=()=>{pendingReceipt=reader.result;renderReceiptPreview()};reader.readAsDataURL(file)});
document.getElementById('entryForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);if(modalType==='time'){const start=f.get('start'),end=f.get('end');let hours=(new Date(`2000-01-01T${end}`)-new Date(`2000-01-01T${start}`))/36e5;if(hours<=0){showToast('End time must be after start time');return}const item={id:editingId||Date.now(),description:String(f.get('description')||'').trim(),job:f.get('project'),date:f.get('date'),start,end,hours,rate:Number(f.get('rate')),currency:f.get('timeCurrency'),billable:f.get('billable')==='on'};editingId?timeEntries=timeEntries.map(x=>x.id===editingId?item:x):timeEntries.unshift(item)}else{const name=f.get('expenseName'),amount=Number(f.get('amount'));if(!name||!amount){showToast('Add an expense name and amount');return}const item={id:editingId||Date.now(),name,amount,category:f.get('category'),job:f.get('expenseProject'),date:f.get('expenseDate')||isoToday,currency:f.get('expenseCurrency'),notes:f.get('notes'),receipt:pendingReceipt};editingId?expenses=expenses.map(x=>x.id===editingId?item:x):expenses.unshift(item)}const msg=editingId?'Entry updated':modalType==='time'?'Time entry saved':'Expense added';renderAll();closeModal();showToast(msg)});

['timeSearch','timePeriodFilter','timeJobFilter','billableFilter','expenseSearch','expensePeriodFilter','expenseJobFilter','categoryFilter'].forEach(id=>document.getElementById(id).addEventListener(id.includes('Search')?'input':'change',()=>{renderTables();renderStats()}));
document.querySelectorAll('[data-feed]').forEach(b=>b.addEventListener('click',()=>{currentFeed=b.dataset.feed;document.querySelectorAll('[data-feed]').forEach(x=>x.classList.toggle('active',x===b));renderActivity()}));
document.getElementById('themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('tw-dark',document.body.classList.contains('dark'))});if(localStorage.getItem('tw-dark')==='true')document.body.classList.add('dark');
document.getElementById('quickCurrency').addEventListener('change',e=>{settings.currency=e.target.value;renderAll();showToast(`Display currency changed to ${settings.currency}`)});
function updateTodayTotal(){const saved=timeEntries.filter(x=>x.date===isoToday).reduce((sum,x)=>sum+x.hours,0),active=timerStart?(Date.now()-timerStart)/36e5:0;document.getElementById('todayTotal').textContent=duration(saved+active)}
function updateTimer(){const seconds=Math.floor((Date.now()-timerStart)/1000),h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;document.getElementById('timerDisplay').textContent=[h,m,s].map(n=>String(n).padStart(2,'0')).join(':');updateTodayTotal()}
document.getElementById('timerButton').addEventListener('click',()=>{const btn=document.getElementById('timerButton');if(!timerStart){timerStart=Date.now();timerTick=setInterval(updateTimer,1000);btn.classList.add('running');btn.innerHTML=ICONS.stop+'<span>Stop & save</span>';document.getElementById('timerStatus').textContent='Tracking now'}else{const hours=Math.max((Date.now()-timerStart)/36e5,.01),job=getJob(document.getElementById('timerProject').value),note=document.getElementById('timerNote').value||'Focused work session';timeEntries.unshift({id:Date.now(),description:note,job:job.name,date:isoToday,start:new Date(timerStart).toTimeString().slice(0,5),end:new Date().toTimeString().slice(0,5),hours,rate:job.rate,currency:job.currency,billable:job.rate>0});clearInterval(timerTick);timerStart=null;btn.classList.remove('running');btn.innerHTML=ICONS.play+'<span>Start timer</span>';document.getElementById('timerStatus').textContent='Ready to focus';document.getElementById('timerDisplay').textContent='00:00:00';document.getElementById('timerNote').value='';renderAll();showToast('Timer saved to your wallet')}});

document.getElementById('jobForm').addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('newJobName').value.trim();if(!name||jobs.some(j=>j.name.toLowerCase()===name.toLowerCase())){showToast('Use a unique job name');return}jobs.push({id:Date.now(),name,color:document.getElementById('newJobColor').value,rate:0,currency:settings.currency});e.target.reset();document.getElementById('newJobColor').value='#6157df';renderAll();showToast('New job added')});
document.getElementById('categoryForm').addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('newCategoryName').value.trim();if(!name||categories.some(c=>c.toLowerCase()===name.toLowerCase())){showToast('Use a unique category name');return}categories.push(name);e.target.reset();renderAll();showToast('Category added')});
document.getElementById('jobList').addEventListener('click',e=>{const save=e.target.closest('[data-save-job]'),del=e.target.closest('[data-delete-job]');if(save){const row=save.closest('[data-job-row]'),job=jobs.find(j=>j.id===Number(save.dataset.saveJob)),old=job.name,name=row.querySelector('.manage-name').value.trim();if(!name){showToast('Job name cannot be empty');return}job.name=name;job.color=row.querySelector('.mini-color').value;job.rate=Number(row.querySelector('.manage-rate').value);job.currency=row.querySelector('.manage-currency').value;timeEntries.forEach(x=>{if(x.job===old)x.job=name});expenses.forEach(x=>{if(x.job===old)x.job=name});if(selectedJob===old)selectedJob=name;renderAll();showToast('Job updated')}if(del){if(jobs.length===1){showToast('Keep at least one job');return}const job=jobs.find(j=>j.id===Number(del.dataset.deleteJob));if(confirm(`Delete ${job.name}? Existing entries will move to ${jobs.find(j=>j.id!==job.id).name}.`)){const replacement=jobs.find(j=>j.id!==job.id).name;timeEntries.forEach(x=>{if(x.job===job.name)x.job=replacement});expenses.forEach(x=>{if(x.job===job.name)x.job=replacement});jobs=jobs.filter(j=>j.id!==job.id);if(selectedJob===job.name)selectedJob='all';renderAll();showToast('Job removed')}}});
document.getElementById('categoryList').addEventListener('click',e=>{const save=e.target.closest('[data-save-category]'),del=e.target.closest('[data-delete-category]');if(save){const i=Number(save.dataset.saveCategory),old=categories[i],name=save.closest('.manage-row').querySelector('.manage-name').value.trim();if(!name){showToast('Category name cannot be empty');return}categories[i]=name;expenses.forEach(x=>{if(x.category===old)x.category=name});renderAll();showToast('Category updated')}if(del){if(categories.length===1){showToast('Keep at least one category');return}const i=Number(del.dataset.deleteCategory),old=categories[i],replacement=categories.find((_,n)=>n!==i);if(confirm(`Delete ${old}? Existing expenses will move to ${replacement}.`)){expenses.forEach(x=>{if(x.category===old)x.category=replacement});categories.splice(i,1);renderAll();showToast('Category removed')}}});
document.getElementById('saveSettings').addEventListener('click',()=>{settings.name=document.getElementById('settingName').value.trim()||'User';settings.workspace=document.getElementById('settingWorkspace').value.trim()||'My workspace';settings.currency=document.getElementById('settingCurrency').value;renderAll();setView('settings');showToast('Settings saved')});

function exportRows(){return[
  ...timeEntries.map(x=>({Type:'Time',Description:x.description,Job:x.job,Date:x.date,Start:x.start,End:x.end,Hours:x.hours,'Hourly Rate':x.rate,Currency:x.currency,Billable:x.billable?'Yes':'No',Amount:Number((x.hours*x.rate).toFixed(2)),Category:'',Notes:''})),
  ...expenses.map(x=>({Type:'Expense',Description:x.name,Job:x.job,Date:x.date,Start:'',End:'',Hours:'','Hourly Rate':'',Currency:x.currency,Billable:'',Amount:x.amount,Category:x.category,Notes:x.notes||''}))
]}
function exportCSV(){const ws=XLSX.utils.json_to_sheet(exportRows());const csv=XLSX.utils.sheet_to_csv(ws);downloadBlob(new Blob([csv],{type:'text/csv;charset=utf-8'}),'timewallet-data.csv');showToast('CSV exported')}
function exportExcel(){const wb=XLSX.utils.book_new(),timeSheet=XLSX.utils.json_to_sheet(timeEntries.map(x=>({Description:x.description,Job:x.job,Date:x.date,Start:x.start,End:x.end,Hours:x.hours,'Hourly Rate':x.rate,Currency:x.currency,Billable:x.billable?'Yes':'No'}))),expenseSheet=XLSX.utils.json_to_sheet(expenses.map(x=>({Expense:x.name,Amount:x.amount,Currency:x.currency,Category:x.category,Job:x.job,Date:x.date,Notes:x.notes||''}))),jobSheet=XLSX.utils.json_to_sheet(jobs.map(x=>({Job:x.name,Color:x.color,'Default Rate':x.rate,Currency:x.currency}))),categorySheet=XLSX.utils.aoa_to_sheet([['Category'],...categories.map(x=>[x])]),settingsSheet=XLSX.utils.json_to_sheet([{Name:settings.name,Workspace:settings.workspace,'Weekly Goal':settings.goal,'Display Currency':settings.currency,...Object.fromEntries(Object.entries(settings.rates).map(([k,v])=>[`Rate ${k}`,v]))}]);XLSX.utils.book_append_sheet(wb,timeSheet,'Time Entries');XLSX.utils.book_append_sheet(wb,expenseSheet,'Expenses');XLSX.utils.book_append_sheet(wb,jobSheet,'Jobs');XLSX.utils.book_append_sheet(wb,categorySheet,'Categories');XLSX.utils.book_append_sheet(wb,settingsSheet,'Settings');XLSX.writeFile(wb,'timewallet-backup.xlsx',{compression:true});showToast('Excel workbook exported')}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.getElementById('exportCsvBtn').addEventListener('click',exportCSV);document.getElementById('exportExcelBtn').addEventListener('click',exportExcel);document.getElementById('importBtn').addEventListener('click',()=>document.getElementById('importFile').click());
document.getElementById('importFile').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:false}),getRows=name=>wb.Sheets[name]?XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:''}):[],combined=wb.SheetNames.length===1?getRows(wb.SheetNames[0]):[];let tRows=getRows('Time Entries'),eRows=getRows('Expenses');if(combined.length){tRows=combined.filter(r=>String(r.Type).toLowerCase()==='time');eRows=combined.filter(r=>String(r.Type).toLowerCase()==='expense')}const importedTime=tRows.map((r,i)=>({id:Date.now()+i,description:r.Description||r.description||'Imported time',job:r.Job||r.Project||jobs[0].name,date:normalizeDate(r.Date),start:r.Start||'09:00',end:r.End||'10:00',hours:Number(r.Hours)||1,rate:Number(r['Hourly Rate']??r.Rate)||0,currency:String(r.Currency||settings.currency).toUpperCase(),billable:String(r.Billable||'Yes').toLowerCase()!=='no'}));const importedExpenses=eRows.map((r,i)=>({id:Date.now()+10000+i,name:r.Expense||r.Description||'Imported expense',amount:Number(r.Amount)||0,category:r.Category||categories[0],job:r.Job||r.Project||jobs[0].name,date:normalizeDate(r.Date),currency:String(r.Currency||settings.currency).toUpperCase(),notes:r.Notes||''})).filter(x=>x.amount);const importedJobs=getRows('Jobs');importedJobs.forEach((r,i)=>{const name=r.Job||r.Name;if(name&&!jobs.some(j=>j.name===name))jobs.push({id:Date.now()+20000+i,name,color:r.Color||'#6157df',rate:Number(r['Default Rate'])||0,currency:r.Currency||settings.currency})});const importedCategories=getRows('Categories');importedCategories.forEach(r=>{const c=r.Category||Object.values(r)[0];if(c&&!categories.includes(c))categories.push(c)});timeEntries=[...importedTime,...timeEntries];expenses=[...importedExpenses,...expenses];renderAll();showToast(`Imported ${importedTime.length} time and ${importedExpenses.length} expense entries`)}catch(err){console.error(err);showToast('Could not import this file')}finally{e.target.value=''}});
function normalizeDate(v){if(!v)return isoToday;if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`}const d=new Date(v);return Number.isNaN(d.getTime())?isoToday:toISO(d)}
function showToast(msg){const t=document.getElementById('toast');t.querySelector('span:last-child').textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2700)}

let rateFetchInFlight=false;async function loadLiveRates(){if(rateFetchInFlight)return;rateFetchInFlight=true;try{rateStatus='Checking live rates…';renderSettings();const rateBase=location.protocol==='file:'?'http://127.0.0.1:43128':'',rateUrl=`${rateBase}/api/wise-rates?_=${Math.floor(Date.now()/60000)}`;let response=await fetch(rateUrl,{cache:'no-store'}),data;if(response.ok)data=await response.json();else{response=await fetch(`https://fxapi.app/api/usd.json?_=${Math.floor(Date.now()/60000)}`,{cache:'no-store'});if(!response.ok)throw new Error('Rate services unavailable');data=await response.json();data.provider='Live market'}if(data.rates?.USD_INR&&!data.rates?.INR){const usdInr=Number(data.rates.USD_INR),ilsInr=Number(data.rates.ILS_INR);data.rates={...data.rates,USD:1,INR:usdInr,ILS:usdInr/ilsInr}}if(!data.rates?.INR||!data.rates?.ILS)throw new Error('Required live rates unavailable');const liveRates={USD:1};Object.keys(CURRENCIES).forEach(code=>{const unitsPerUsd=Number(data.rates?.[code]);if(unitsPerUsd>0)liveRates[code]=1/unitsPerUsd});settings.rates={...settings.rates,...liveRates};rateUpdatedAt=data.timestamp||new Date().toISOString();localStorage.setItem('tw-rate-updated',rateUpdatedAt);rateStatus=`${data.provider||'Live'} · ${new Date(rateUpdatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`;renderAll()}catch(error){console.warn('Live currency update unavailable; cached rates are being used.',error);rateStatus=rateUpdatedAt?`Cached · ${new Date(rateUpdatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`:'Offline fallback';renderAll()}finally{rateFetchInFlight=false}}
function updateCurrentTime(){document.getElementById('currentTime').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}

decorateIcons();renderAll();setView('dashboard');updateCurrentTime();setInterval(updateCurrentTime,1000);loadLiveRates();setInterval(loadLiveRates,60000);
